services:
  - type: web
    name: habitat
    runtime: node
    buildCommand: ""
    startCommand: node serve.js
    envVars:
      - key: NASS_API_KEY
        sync: false
      - key: EBIRD_API_KEY
        sync: false
      - key: NOAA_CDO_TOKEN
        sync: false
